litellm_settings:
  drop_params: true
  set_verbose: true
model_list:
- litellm_params:
    api_base: http://127.0.0.1:11434
    headers:
      HTTP-Referer: litellm.ai
      X-Title: LiteLLM Server
    model: ollama/openchat
  model_name: gpt-4-1106-preview
- litellm_params:
    api_base: http://127.0.0.1:11434
    headers:
      HTTP-Referer: litellm.ai
      X-Title: LiteLLM Server
    model: ollama/openchat
  model_name: gpt-4
- litellm_params:
    api_base: http://127.0.0.1:11434
    headers:
      HTTP-Referer: litellm.ai
      X-Title: LiteLLM Server
    model: ollama/openchat
  model_name: gpt-3.5-turbo
- litellm_params:
    api_base: http://127.0.0.1:11434
    headers:
      HTTP-Referer: litellm.ai
      X-Title: LiteLLM Server
    model: ollama/llava
  model_name: gpt-4-vision-preview